version: '3.3'

services:
  db-pgsql-nestjs:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_nestjs
    restart: always
    env_file:
      - .env
    ports:
      - 8081:80

volumes:
  pgdata:
